[theme]
base="dark"
primaryColor="#00C0F2"
backgroundColor="#0e1117"
secondaryBackgroundColor="#1f232c"
textColor="#f6f6f6"
font="sans serif"

[server]
runOnSave = true

[client]
showErrorDetails = true

